# Generated by Django 5.2 on 2025-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormPrediccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sexo", models.CharField()),
                ("edad", models.IntegerField()),
                ("estatura", models.FloatField()),
                ("peso", models.FloatField()),
                ("antecedentes_fam", models.CharField()),
                ("favc", models.CharField()),
                ("fcvc", models.CharField()),
                ("ncp", models.IntegerField()),
                ("caec", models.CharField()),
                ("ch20", models.CharField()),
                ("scc", models.CharField()),
                ("faf", models.CharField()),
                ("tue", models.CharField()),
                ("calc", models.CharField()),
                ("smoke", models.CharField()),
                ("mtrans", models.CharField()),
            ],
        ),
    ]
